version: '3'

services:
  commentapp:
    image: stanleynguyen/gitcomment_comment
    ports:
      - 5000:5000
    deploy:
      replicas: 5
      restart_policy:
        max_attempts: 3
        condition: on-failure
      update_config:
        parallelism: 3
        delay: 10s
    environment:
      - GO_ENV=production
      - PORT=5000
      - DB=postgres://${PG_USER}:${PG_PSSWD}@gitcommentapp_postgres:5432/${PG_DB}
    networks:
      - balance

  memberapp:
    image: stanleynguyen/gitcomment_member
    ports:
      - 5001:5001
    deploy:
      replicas: 5
      restart_policy:
        max_attempts: 3
        condition: on-failure
      update_config:
        parallelism: 3
        delay: 10s
    environment:
      - NODE_ENV=production
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    networks:
      - balance

  proxy:
    image: stanleynguyen/gitcomment_proxy
    ports:
      - 80:80
    depends_on:
      - commentapp
      - memberapp
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - balance

  postgres:
    image: postgres:alpine
    container_name: gitcommentapp_postgres
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PSSWD}
      - POSTGRES_DB=${PG_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - balance_dev

networks:
  balance:
    driver: overlay
